// +FHDR------------------------------------------------------------------------
// Copyright ownership belongs to CAG laboratory, Institute of Artificial
// Intelligence and Robotics, Xi'an Jiaotong University, shall not be used in
// commercial ways without permission.
// -----------------------------------------------------------------------------
// FILE NAME  : global.h
// DEPARTMENT : CAG of IAIR
// AUTHOR     : XXXX
// AUTHOR'S EMAIL :XXXX@mail.xjtu.edu.cn
// -----------------------------------------------------------------------------
// Ver 1.0  2019--01--01 initial version.
// -----------------------------------------------------------------------------

#ifndef GLOBAL_H
#define GLOBAL_H

#ifdef __cpluscplus
extern "C" {
#endif

#define DDR_WT_BASE_ADDR 0x00000000
#define DDR_BS_BASE_ADDR 0x00300000
#define DDR_FM_BASE_ADDR 0x00350000

// stage status indication
#define PHASE_CONV1_IS_ACTIVE  1
#define PHASE_BLK1_1_IS_ACTIVE 1
#define PHASE_BLK2_1_IS_ACTIVE 1
#define PHASE_BLK3_1_IS_ACTIVE 1
#define PHASE_BLK4_1_IS_ACTIVE 1
#define PHASE_BLK5_1_IS_ACTIVE 1
#define PHASE_BLK6_1_IS_ACTIVE 1
#define PHASE_CONVF_IS_ACTIVE  1

// ==================================================================
// weight distribution
// ==================================================================
#define DDR_TOT_WT_LEN 31833

#define DDR_CONV1_WT_ADDR DDR_WT_BASE_ADDR
#define DDR_CONV1_WT_LEN 18

#define DDR_B1_1_DWC_WT_ADDR DDR_CONV1_WT_ADDR + (DDR_CONV1_WT_LEN << 6)
#define DDR_B1_1_DWC_WT_LEN 99
#define DDR_B1_1_CONV_WT_ADDR DDR_B1_1_DWC_WT_ADDR + (DDR_B1_1_DWC_WT_LEN << 6)
#define DDR_B1_1_CONV_WT_LEN 112

#define DDR_B2_1_DWC_WT_ADDR DDR_B1_1_CONV_WT_ADDR + (DDR_B1_1_CONV_WT_LEN << 6)
#define DDR_B2_1_DWC_WT_LEN 72
#define DDR_B2_1_CONV_WT_ADDR DDR_B2_1_DWC_WT_ADDR + (DDR_B2_1_DWC_WT_LEN << 6)
#define DDR_B2_1_CONV_WT_LEN 128

#define DDR_B2_2_DWC_WT_ADDR DDR_B2_1_CONV_WT_ADDR + (DDR_B2_1_CONV_WT_LEN << 6)
#define DDR_B2_2_DWC_WT_LEN 72
#define DDR_B2_2_CONV_WT_ADDR DDR_B2_2_DWC_WT_ADDR + (DDR_B2_2_DWC_WT_LEN << 6)
#define DDR_B2_2_CONV_WT_LEN 128

#define DDR_B2_3_DWC_WT_ADDR DDR_B2_2_CONV_WT_ADDR + (DDR_B2_2_CONV_WT_LEN << 6)
#define DDR_B2_3_DWC_WT_LEN 72
#define DDR_B2_3_CONV_WT_ADDR DDR_B2_3_DWC_WT_ADDR + (DDR_B2_3_DWC_WT_LEN << 6)
#define DDR_B2_3_CONV_WT_LEN 128

#define DDR_B3_1_DWC_WT_ADDR DDR_B2_3_CONV_WT_ADDR + (DDR_B2_3_CONV_WT_LEN << 6)
#define DDR_B3_1_DWC_WT_LEN 288
#define DDR_B3_1_CONV_WT_ADDR DDR_B3_1_DWC_WT_ADDR + (DDR_B3_1_DWC_WT_LEN << 6)
#define DDR_B3_1_CONV_WT_LEN 768

#define DDR_B4_1_DWC_WT_ADDR DDR_B3_1_CONV_WT_ADDR + (DDR_B3_1_CONV_WT_LEN << 6)
#define DDR_B4_1_DWC_WT_LEN 144
#define DDR_B4_1_CONV_WT_ADDR DDR_B4_1_DWC_WT_ADDR + (DDR_B4_1_DWC_WT_LEN << 6)
#define DDR_B4_1_CONV_WT_LEN 512

#define DDR_B4_2_DWC_WT_ADDR DDR_B4_1_CONV_WT_ADDR + (DDR_B4_1_CONV_WT_LEN << 6)
#define DDR_B4_2_DWC_WT_LEN 144
#define DDR_B4_2_CONV_WT_ADDR DDR_B4_2_DWC_WT_ADDR + (DDR_B4_2_DWC_WT_LEN << 6)
#define DDR_B4_2_CONV_WT_LEN 512

#define DDR_B4_3_DWC_WT_ADDR DDR_B4_2_CONV_WT_ADDR + (DDR_B4_2_CONV_WT_LEN << 6)
#define DDR_B4_3_DWC_WT_LEN 144
#define DDR_B4_3_CONV_WT_ADDR DDR_B4_3_DWC_WT_ADDR + (DDR_B4_3_DWC_WT_LEN << 6)
#define DDR_B4_3_CONV_WT_LEN 512

#define DDR_B4_4_DWC_WT_ADDR DDR_B4_3_CONV_WT_ADDR + (DDR_B4_3_CONV_WT_LEN << 6)
#define DDR_B4_4_DWC_WT_LEN 144
#define DDR_B4_4_CONV_WT_ADDR DDR_B4_4_DWC_WT_ADDR + (DDR_B4_4_DWC_WT_LEN << 6)
#define DDR_B4_4_CONV_WT_LEN 512

#define DDR_B4_5_DWC_WT_ADDR DDR_B4_4_CONV_WT_ADDR + (DDR_B4_4_CONV_WT_LEN << 6)
#define DDR_B4_5_DWC_WT_LEN 144
#define DDR_B4_5_CONV_WT_ADDR DDR_B4_5_DWC_WT_ADDR + (DDR_B4_5_DWC_WT_LEN << 6)
#define DDR_B4_5_CONV_WT_LEN 512

#define DDR_B4_6_DWC_WT_ADDR DDR_B4_5_CONV_WT_ADDR + (DDR_B4_5_CONV_WT_LEN << 6)
#define DDR_B4_6_DWC_WT_LEN 144
#define DDR_B4_6_CONV_WT_ADDR DDR_B4_6_DWC_WT_ADDR + (DDR_B4_6_DWC_WT_LEN << 6)
#define DDR_B4_6_CONV_WT_LEN 512

#define DDR_B4_7_DWC_WT_ADDR DDR_B4_6_CONV_WT_ADDR + (DDR_B4_6_CONV_WT_LEN << 6)
#define DDR_B4_7_DWC_WT_LEN 144
#define DDR_B4_7_CONV_WT_ADDR DDR_B4_7_DWC_WT_ADDR + (DDR_B4_7_DWC_WT_LEN << 6)
#define DDR_B4_7_CONV_WT_LEN 512

#define DDR_B5_1_DWC_WT_ADDR DDR_B4_7_CONV_WT_ADDR + (DDR_B4_7_CONV_WT_LEN << 6)
#define DDR_B5_1_DWC_WT_LEN 72
#define DDR_B5_1_CONV_WT_ADDR DDR_B5_1_DWC_WT_ADDR + (DDR_B5_1_DWC_WT_LEN << 6)
#define DDR_B5_1_CONV_WT_LEN 3072

#define DDR_B6_1_DWC_WT_ADDR DDR_B5_1_CONV_WT_ADDR + (DDR_B5_1_CONV_WT_LEN << 6)
#define DDR_B6_1_DWC_WT_LEN 36
#define DDR_B6_1_CONV_WT_ADDR DDR_B6_1_DWC_WT_ADDR + (DDR_B6_1_DWC_WT_LEN << 6)
#define DDR_B6_1_CONV_WT_LEN 2048

#define DDR_B6_2_DWC_WT_ADDR DDR_B6_1_CONV_WT_ADDR + (DDR_B6_1_CONV_WT_LEN << 6)
#define DDR_B6_2_DWC_WT_LEN 36
#define DDR_B6_2_CONV_WT_ADDR DDR_B6_2_DWC_WT_ADDR + (DDR_B6_2_DWC_WT_LEN << 6)
#define DDR_B6_2_CONV_WT_LEN 2048

#define DDR_B6_3_DWC_WT_ADDR DDR_B6_2_CONV_WT_ADDR + (DDR_B6_2_CONV_WT_LEN << 6)
#define DDR_B6_3_DWC_WT_LEN 36
#define DDR_B6_3_CONV_WT_ADDR DDR_B6_3_DWC_WT_ADDR + (DDR_B6_3_DWC_WT_LEN << 6)
#define DDR_B6_3_CONV_WT_LEN 2048

#define DDR_B6_4_DWC_WT_ADDR DDR_B6_3_CONV_WT_ADDR + (DDR_B6_3_CONV_WT_LEN << 6)
#define DDR_B6_4_DWC_WT_LEN 36
#define DDR_B6_4_CONV_WT_ADDR DDR_B6_4_DWC_WT_ADDR + (DDR_B6_4_DWC_WT_LEN << 6)
#define DDR_B6_4_CONV_WT_LEN 2048

#define DDR_B6_5_DWC_WT_ADDR DDR_B6_4_CONV_WT_ADDR + (DDR_B6_4_CONV_WT_LEN << 6)
#define DDR_B6_5_DWC_WT_LEN 36
#define DDR_B6_5_CONV_WT_ADDR DDR_B6_5_DWC_WT_ADDR + (DDR_B6_5_DWC_WT_LEN << 6)
#define DDR_B6_5_CONV_WT_LEN 2048

#define DDR_B6_6_DWC_WT_ADDR DDR_B6_5_CONV_WT_ADDR + (DDR_B6_5_CONV_WT_LEN << 6)
#define DDR_B6_6_DWC_WT_LEN 36
#define DDR_B6_6_CONV_WT_ADDR DDR_B6_6_DWC_WT_ADDR + (DDR_B6_6_DWC_WT_LEN << 6)
#define DDR_B6_6_CONV_WT_LEN 2048

#define DDR_B6_7_DWC_WT_ADDR DDR_B6_6_CONV_WT_ADDR + (DDR_B6_6_CONV_WT_LEN << 6)
#define DDR_B6_7_DWC_WT_LEN 36
#define DDR_B6_7_CONV_WT_ADDR DDR_B6_7_DWC_WT_ADDR + (DDR_B6_7_DWC_WT_LEN << 6)
#define DDR_B6_7_CONV_WT_LEN 2048

#define DDR_B6_8_DWC_WT_ADDR DDR_B6_7_CONV_WT_ADDR + (DDR_B6_7_CONV_WT_LEN << 6)
#define DDR_B6_8_DWC_WT_LEN 36
#define DDR_B6_8_CONV_WT_ADDR DDR_B6_8_DWC_WT_ADDR + (DDR_B6_8_DWC_WT_LEN << 6)
#define DDR_B6_8_CONV_WT_LEN 2048

#define DDR_B6_9_DWC_WT_ADDR DDR_B6_8_CONV_WT_ADDR + (DDR_B6_8_CONV_WT_LEN << 6)
#define DDR_B6_9_DWC_WT_LEN 36
#define DDR_B6_9_CONV_WT_ADDR DDR_B6_9_DWC_WT_ADDR + (DDR_B6_9_DWC_WT_LEN << 6)
#define DDR_B6_9_CONV_WT_LEN 2048

#define DDR_CONVF_WT_ADDR DDR_B6_9_CONV_WT_ADDR + (DDR_B6_9_CONV_WT_LEN << 6)
#define DDR_CONVF_WT_LEN 3456

// ==================================================================
// bias distribution
// ==================================================================
#define DDR_TOT_BS_LEN 1304

#define DDR_CONV1_BS_ADDR DDR_BS_BASE_ADDR
#define DDR_CONV1_BS_LEN 3

#define DDR_B1_1_DWC_BS_ADDR DDR_CONV1_BS_ADDR + (DDR_CONV1_BS_LEN << 6)
#define DDR_B1_1_DWC_BS_LEN 11
#define DDR_B1_1_CONV_BS_ADDR DDR_B1_1_DWC_BS_ADDR + (DDR_B1_1_DWC_BS_LEN << 6)
#define DDR_B1_1_CONV_BS_LEN 24

#define DDR_B2_1_DWC_BS_ADDR DDR_B1_1_CONV_BS_ADDR + (DDR_B1_1_CONV_BS_LEN << 6)
#define DDR_B2_1_DWC_BS_LEN 8
#define DDR_B2_1_CONV_BS_ADDR DDR_B2_1_DWC_BS_ADDR + (DDR_B2_1_DWC_BS_LEN << 6)
#define DDR_B2_1_CONV_BS_LEN 16

#define DDR_B2_2_DWC_BS_ADDR DDR_B2_1_CONV_BS_ADDR + (DDR_B2_1_CONV_BS_LEN << 6)
#define DDR_B2_2_DWC_BS_LEN 8
#define DDR_B2_2_CONV_BS_ADDR DDR_B2_2_DWC_BS_ADDR + (DDR_B2_2_DWC_BS_LEN << 6)
#define DDR_B2_2_CONV_BS_LEN 16

#define DDR_B2_3_DWC_BS_ADDR DDR_B2_2_CONV_BS_ADDR + (DDR_B2_2_CONV_BS_LEN << 6)
#define DDR_B2_3_DWC_BS_LEN 8
#define DDR_B2_3_CONV_BS_ADDR DDR_B2_3_DWC_BS_ADDR + (DDR_B2_3_DWC_BS_LEN << 6)
#define DDR_B2_3_CONV_BS_LEN 16

#define DDR_B3_1_DWC_BS_ADDR DDR_B2_3_CONV_BS_ADDR + (DDR_B2_3_CONV_BS_LEN << 6)
#define DDR_B3_1_DWC_BS_LEN 32
#define DDR_B3_1_CONV_BS_ADDR DDR_B3_1_DWC_BS_ADDR + (DDR_B3_1_DWC_BS_LEN << 6)
#define DDR_B3_1_CONV_BS_LEN 48

#define DDR_B4_1_DWC_BS_ADDR DDR_B3_1_CONV_BS_ADDR + (DDR_B3_1_CONV_BS_LEN << 6)
#define DDR_B4_1_DWC_BS_LEN 16
#define DDR_B4_1_CONV_BS_ADDR DDR_B4_1_DWC_BS_ADDR + (DDR_B4_1_DWC_BS_LEN << 6)
#define DDR_B4_1_CONV_BS_LEN 32

#define DDR_B4_2_DWC_BS_ADDR DDR_B4_1_CONV_BS_ADDR + (DDR_B4_1_CONV_BS_LEN << 6)
#define DDR_B4_2_DWC_BS_LEN 16
#define DDR_B4_2_CONV_BS_ADDR DDR_B4_2_DWC_BS_ADDR + (DDR_B4_2_DWC_BS_LEN << 6)
#define DDR_B4_2_CONV_BS_LEN 32

#define DDR_B4_3_DWC_BS_ADDR DDR_B4_2_CONV_BS_ADDR + (DDR_B4_2_CONV_BS_LEN << 6)
#define DDR_B4_3_DWC_BS_LEN 16
#define DDR_B4_3_CONV_BS_ADDR DDR_B4_3_DWC_BS_ADDR + (DDR_B4_3_DWC_BS_LEN << 6)
#define DDR_B4_3_CONV_BS_LEN 32

#define DDR_B4_4_DWC_BS_ADDR DDR_B4_3_CONV_BS_ADDR + (DDR_B4_3_CONV_BS_LEN << 6)
#define DDR_B4_4_DWC_BS_LEN 16
#define DDR_B4_4_CONV_BS_ADDR DDR_B4_4_DWC_BS_ADDR + (DDR_B4_4_DWC_BS_LEN << 6)
#define DDR_B4_4_CONV_BS_LEN 32

#define DDR_B4_5_DWC_BS_ADDR DDR_B4_4_CONV_BS_ADDR + (DDR_B4_4_CONV_BS_LEN << 6)
#define DDR_B4_5_DWC_BS_LEN 16
#define DDR_B4_5_CONV_BS_ADDR DDR_B4_5_DWC_BS_ADDR + (DDR_B4_5_DWC_BS_LEN << 6)
#define DDR_B4_5_CONV_BS_LEN 32

#define DDR_B4_6_DWC_BS_ADDR DDR_B4_5_CONV_BS_ADDR + (DDR_B4_5_CONV_BS_LEN << 6)
#define DDR_B4_6_DWC_BS_LEN 16
#define DDR_B4_6_CONV_BS_ADDR DDR_B4_6_DWC_BS_ADDR + (DDR_B4_6_DWC_BS_LEN << 6)
#define DDR_B4_6_CONV_BS_LEN 32

#define DDR_B4_7_DWC_BS_ADDR DDR_B4_6_CONV_BS_ADDR + (DDR_B4_6_CONV_BS_LEN << 6)
#define DDR_B4_7_DWC_BS_LEN 16
#define DDR_B4_7_CONV_BS_ADDR DDR_B4_7_DWC_BS_ADDR + (DDR_B4_7_DWC_BS_LEN << 6)
#define DDR_B4_7_CONV_BS_LEN 32

#define DDR_B5_1_DWC_BS_ADDR DDR_B4_7_CONV_BS_ADDR + (DDR_B4_7_CONV_BS_LEN << 6)
#define DDR_B5_1_DWC_BS_LEN 8
#define DDR_B5_1_CONV_BS_ADDR DDR_B5_1_DWC_BS_ADDR + (DDR_B5_1_DWC_BS_LEN << 6)
#define DDR_B5_1_CONV_BS_LEN 96

#define DDR_B6_1_DWC_BS_ADDR DDR_B5_1_CONV_BS_ADDR + (DDR_B5_1_CONV_BS_LEN << 6)
#define DDR_B6_1_DWC_BS_LEN 4
#define DDR_B6_1_CONV_BS_ADDR DDR_B6_1_DWC_BS_ADDR + (DDR_B6_1_DWC_BS_LEN << 6)
#define DDR_B6_1_CONV_BS_LEN 64

#define DDR_B6_2_DWC_BS_ADDR DDR_B6_1_CONV_BS_ADDR + (DDR_B6_1_CONV_BS_LEN << 6)
#define DDR_B6_2_DWC_BS_LEN 4
#define DDR_B6_2_CONV_BS_ADDR DDR_B6_2_DWC_BS_ADDR + (DDR_B6_2_DWC_BS_LEN << 6)
#define DDR_B6_2_CONV_BS_LEN 64

#define DDR_B6_3_DWC_BS_ADDR DDR_B6_2_CONV_BS_ADDR + (DDR_B6_2_CONV_BS_LEN << 6)
#define DDR_B6_3_DWC_BS_LEN 4
#define DDR_B6_3_CONV_BS_ADDR DDR_B6_3_DWC_BS_ADDR + (DDR_B6_3_DWC_BS_LEN << 6)
#define DDR_B6_3_CONV_BS_LEN 64

#define DDR_B6_4_DWC_BS_ADDR DDR_B6_3_CONV_BS_ADDR + (DDR_B6_3_CONV_BS_LEN << 6)
#define DDR_B6_4_DWC_BS_LEN 4
#define DDR_B6_4_CONV_BS_ADDR DDR_B6_4_DWC_BS_ADDR + (DDR_B6_4_DWC_BS_LEN << 6)
#define DDR_B6_4_CONV_BS_LEN 64

#define DDR_B6_5_DWC_BS_ADDR DDR_B6_4_CONV_BS_ADDR + (DDR_B6_4_CONV_BS_LEN << 6)
#define DDR_B6_5_DWC_BS_LEN 4
#define DDR_B6_5_CONV_BS_ADDR DDR_B6_5_DWC_BS_ADDR + (DDR_B6_5_DWC_BS_LEN << 6)
#define DDR_B6_5_CONV_BS_LEN 64

#define DDR_B6_6_DWC_BS_ADDR DDR_B6_5_CONV_BS_ADDR + (DDR_B6_5_CONV_BS_LEN << 6)
#define DDR_B6_6_DWC_BS_LEN 4
#define DDR_B6_6_CONV_BS_ADDR DDR_B6_6_DWC_BS_ADDR + (DDR_B6_6_DWC_BS_LEN << 6)
#define DDR_B6_6_CONV_BS_LEN 64

#define DDR_B6_7_DWC_BS_ADDR DDR_B6_6_CONV_BS_ADDR + (DDR_B6_6_CONV_BS_LEN << 6)
#define DDR_B6_7_DWC_BS_LEN 4
#define DDR_B6_7_CONV_BS_ADDR DDR_B6_7_DWC_BS_ADDR + (DDR_B6_7_DWC_BS_LEN << 6)
#define DDR_B6_7_CONV_BS_LEN 64

#define DDR_B6_8_DWC_BS_ADDR DDR_B6_7_CONV_BS_ADDR + (DDR_B6_7_CONV_BS_LEN << 6)
#define DDR_B6_8_DWC_BS_LEN 4
#define DDR_B6_8_CONV_BS_ADDR DDR_B6_8_DWC_BS_ADDR + (DDR_B6_8_DWC_BS_LEN << 6)
#define DDR_B6_8_CONV_BS_LEN 64

#define DDR_B6_9_DWC_BS_ADDR DDR_B6_8_CONV_BS_ADDR + (DDR_B6_8_CONV_BS_LEN << 6)
#define DDR_B6_9_DWC_BS_LEN 4
#define DDR_B6_9_CONV_BS_ADDR DDR_B6_9_DWC_BS_ADDR + (DDR_B6_9_DWC_BS_LEN << 6)
#define DDR_B6_9_CONV_BS_LEN 64

#define DDR_CONVF_BS_ADDR DDR_B6_9_CONV_BS_ADDR + (DDR_B6_9_CONV_BS_LEN << 6)
#define DDR_CONVF_BS_LEN 6

// ==================================================================
// feature map distribution
// ==================================================================
#define DDR_CONV1_FM_ADDR DDR_FM_BASE_ADDR
#define DDR_CONV1_FM_LEN 30
#define DDR_CONV1_FM_HEIGHT 360

#define DDR_B1_1_FM_ADDR DDR_CONV1_FM_ADDR + (DDR_CONV1_FM_LEN << 6)*DDR_CONV1_FM_HEIGHT
#define DDR_B1_1_FM_LEN 60
#define DDR_B1_1_FM_HEIGHT 90

#define DDR_B2_1_FM_ADDR DDR_B1_1_FM_ADDR + (DDR_B1_1_FM_LEN << 6)*DDR_B1_1_FM_HEIGHT
#define DDR_B2_1_FM_LEN 160
#define DDR_B2_1_FM_HEIGHT 45

#define DDR_B2_2_FM_ADDR DDR_B2_1_FM_ADDR + (DDR_B2_1_FM_LEN << 6)*DDR_B2_1_FM_HEIGHT
#define DDR_B2_2_FM_LEN 160
#define DDR_B2_2_FM_HEIGHT 45

#define DDR_B2_3_FM_ADDR DDR_B2_2_FM_ADDR + (DDR_B2_2_FM_LEN << 6)*DDR_B2_2_FM_HEIGHT
#define DDR_B2_3_FM_LEN 160
#define DDR_B2_3_FM_HEIGHT 45

#define DDR_B3_1_FM_ADDR DDR_B2_3_FM_ADDR + (DDR_B2_3_FM_LEN << 6)*DDR_B2_3_FM_HEIGHT
#define DDR_B3_1_FM_LEN 160
#define DDR_B3_1_FM_HEIGHT 45

#define DDR_B4_1_FM_ADDR DDR_B3_1_FM_ADDR + (DDR_B3_1_FM_LEN << 6)*DDR_B3_1_FM_HEIGHT
#define DDR_B4_1_FM_LEN 160
#define DDR_B4_1_FM_HEIGHT 23

#define DDR_B4_2_FM_ADDR DDR_B4_1_FM_ADDR + (DDR_B4_1_FM_LEN << 6)*DDR_B4_1_FM_HEIGHT
#define DDR_B4_2_FM_LEN 160
#define DDR_B4_2_FM_HEIGHT 23

#define DDR_B4_3_FM_ADDR DDR_B4_2_FM_ADDR + (DDR_B4_2_FM_LEN << 6)*DDR_B4_2_FM_HEIGHT
#define DDR_B4_3_FM_LEN 160
#define DDR_B4_3_FM_HEIGHT 23

#define DDR_B4_4_FM_ADDR DDR_B4_3_FM_ADDR + (DDR_B4_3_FM_LEN << 6)*DDR_B4_3_FM_HEIGHT
#define DDR_B4_4_FM_LEN 160
#define DDR_B4_4_FM_HEIGHT 23

#define DDR_B4_5_FM_ADDR DDR_B4_4_FM_ADDR + (DDR_B4_4_FM_LEN << 6)*DDR_B4_4_FM_HEIGHT
#define DDR_B4_5_FM_LEN 160
#define DDR_B4_5_FM_HEIGHT 23

#define DDR_B4_6_FM_ADDR DDR_B4_5_FM_ADDR + (DDR_B4_5_FM_LEN << 6)*DDR_B4_5_FM_HEIGHT
#define DDR_B4_6_FM_LEN 160
#define DDR_B4_6_FM_HEIGHT 23

#define DDR_B4_7_FM_ADDR DDR_B4_6_FM_ADDR + (DDR_B4_6_FM_LEN << 6)*DDR_B4_6_FM_HEIGHT
#define DDR_B4_7_FM_LEN 160
#define DDR_B4_7_FM_HEIGHT 23

#define DDR_B5_1_FM_ADDR DDR_B4_7_FM_ADDR + (DDR_B4_7_FM_LEN << 6)*DDR_B4_7_FM_HEIGHT
#define DDR_B5_1_FM_LEN 160
#define DDR_B5_1_FM_HEIGHT 23

#define DDR_B6_1_FM_ADDR DDR_B5_1_FM_ADDR + (DDR_B5_1_FM_LEN << 6)*DDR_B5_1_FM_HEIGHT
#define DDR_B6_1_FM_LEN 160
#define DDR_B6_1_FM_HEIGHT 12

#define DDR_B6_2_FM_ADDR DDR_B6_1_FM_ADDR + (DDR_B6_1_FM_LEN << 6)*DDR_B6_1_FM_HEIGHT
#define DDR_B6_2_FM_LEN 160
#define DDR_B6_2_FM_HEIGHT 12

#define DDR_B6_3_FM_ADDR DDR_B6_2_FM_ADDR + (DDR_B6_2_FM_LEN << 6)*DDR_B6_2_FM_HEIGHT
#define DDR_B6_3_FM_LEN 160
#define DDR_B6_3_FM_HEIGHT 12

#define DDR_B6_4_FM_ADDR DDR_B6_3_FM_ADDR + (DDR_B6_3_FM_LEN << 6)*DDR_B6_3_FM_HEIGHT
#define DDR_B6_4_FM_LEN 160
#define DDR_B6_4_FM_HEIGHT 12

#define DDR_B6_5_FM_ADDR DDR_B6_4_FM_ADDR + (DDR_B6_4_FM_LEN << 6)*DDR_B6_4_FM_HEIGHT
#define DDR_B6_5_FM_LEN 160
#define DDR_B6_5_FM_HEIGHT 12

#define DDR_B6_6_FM_ADDR DDR_B6_5_FM_ADDR + (DDR_B6_5_FM_LEN << 6)*DDR_B6_5_FM_HEIGHT
#define DDR_B6_6_FM_LEN 160
#define DDR_B6_6_FM_HEIGHT 12

#define DDR_B6_7_FM_ADDR DDR_B6_6_FM_ADDR + (DDR_B6_6_FM_LEN << 6)*DDR_B6_6_FM_HEIGHT
#define DDR_B6_7_FM_LEN 160
#define DDR_B6_7_FM_HEIGHT 12

#define DDR_B6_8_FM_ADDR DDR_B6_7_FM_ADDR + (DDR_B6_7_FM_LEN << 6)*DDR_B6_7_FM_HEIGHT
#define DDR_B6_8_FM_LEN 160
#define DDR_B6_8_FM_HEIGHT 12

#define DDR_B6_9_FM_ADDR DDR_B6_8_FM_ADDR + (DDR_B6_8_FM_LEN << 6)*DDR_B6_8_FM_HEIGHT
#define DDR_B6_9_FM_LEN 160
#define DDR_B6_9_FM_HEIGHT 12

#define DDR_CONVF_FM_ADDR DDR_B6_9_FM_ADDR + (DDR_B6_9_FM_LEN << 6)*DDR_B6_9_FM_HEIGHT 
#define DDR_CONVF_FM_LEN 160
#define DDR_CONVF_FM_HEIGHT 12

#define DDR_OUTPUT_FM_ADDR DDR_CONVF_FM_ADDR + (DDR_CONVF_FM_LEN << 6)*DDR_CONVF_FM_HEIGHT 
#define DDR_OUTPUT_FM_LEN 18
#define DDR_OUTPUT_FM_HEIGHT 12

#ifdef __cplusplus
}
#endif

#endif
